<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://www.example.com/namespace" 
           xmlns="http://www.example.com/namespace" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           elementFormDefault="qualified">

    <!-- Definizione del tipo semplice TempoDiConservazioneType -->
    <xs:simpleType name="TempoDiConservazioneType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="9999"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Documento">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Intestazione">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="IdFile" type="xs:string"/>
                            <xs:element name="NomeFile" type="xs:string"/>
                            <xs:element name="Principale" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
        
                <xs:element name="Profilo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MetadatiSpecifici">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="metadatoCustom" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="MetadatiAGID">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!-- Utilizzo del tipo TempoDiConservazioneType -->
                                        <xs:element name="TempoDiConservazione" type="TempoDiConservazioneType" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
