<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="SyncSignService" targetNamespace="http://www.medas-solutions.it/ScrybaSignServer/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.medas-solutions.it/ScrybaSignServer/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
<xs:schema targetNamespace="http://www.medas-solutions.it/ScrybaSignServer/" version="1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.medas-solutions.it/ScrybaSignServer/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:import namespace="http://www.medas-solutions.it/ScrybaSignServer/"/>
            <xs:element name="CertListReq">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="CertListReq" type="tns:typeCertListReq"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="CertListResp">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="CertListResp" type="tns:typeCertListResp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="CloseSignSessionReq">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="CloseSignSessionReq" type="tns:typeCloseSignSessionReq"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="CloseSignSessionResp">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="CloseSignSessionResp" type="tns:typeCloseSignSessionResp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DespatchOtpReq">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="DespatchOtpReq" type="tns:typeDespatchOtpReq"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DespatchOtpResp">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="DespatchOtpResp" type="tns:typeDespatchOtpResp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetUserInfoReq">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="GetUserInfoReq" type="tns:typeGetUserInfoReq"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetUserInfoReq2">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="GetUserInfoReq2" type="tns:typeGetUserInfoReq2"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetUserInfoResp">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="GetUserInfoResp" type="tns:typeGetUserInfoResp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetUserInfoResp2">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="GetUserInfoResp2" type="tns:typeGetUserInfoResp2"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="OpenSignSessionReq">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="OpenSignSessionReq" type="tns:typeOpenSignSessionReq"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="OpenSignSessionResp">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="OpenSignSessionResp" type="tns:typeOpenSignSessionResp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="SignDocReq">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="SignDocReq" type="tns:typeSignDocReq"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="SignDocResp">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="SignDocResp" type="tns:typeSignDocResp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="SignOneDocReq">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="SignOneDocReq" type="tns:typeSignOneDocReq"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="SignOneDocResp">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="SignOneDocResp" type="tns:typeSignOneDocResp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:complexType name="typeCertListReq">
                <xs:sequence>
                    <xs:element name="user" type="tns:typeUser"/>
                    <xs:element name="credentials" type="tns:typeCredentials"/>
                    <xs:element minOccurs="0" name="certificateId" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeUser">
                <xs:sequence>
                    <xs:element minOccurs="0" name="username" type="xs:string"/>
                    <xs:element minOccurs="0" name="firstName" type="xs:string"/>
                    <xs:element minOccurs="0" name="lastName" type="xs:string"/>
                    <xs:element minOccurs="0" name="ssn" type="xs:string"/>
                    <xs:element minOccurs="0" name="birthDate" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeCredentials">
                <xs:sequence>
                    <xs:element name="password" type="xs:string"/>
                    <xs:element minOccurs="0" name="otp" type="xs:string"/>
                    <xs:element minOccurs="0" name="type" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeCertListResp">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="rawCertificates" nillable="true" type="tns:typeRawCertificate"/>
                    <xs:element name="message" type="tns:typeMessage"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeRawCertificate">
                <xs:sequence>
                    <xs:element name="serialNumber" type="xs:string"/>
                    <xs:element name="certificate" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeMessage">
                <xs:sequence>
                    <xs:element name="code" type="xs:integer"/>
                    <xs:element minOccurs="0" name="message" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeOpenSignSessionReq">
                <xs:sequence>
                    <xs:element minOccurs="0" name="automatic" type="xs:boolean"/>
                    <xs:element name="user" type="tns:typeUser"/>
                    <xs:element name="credentials" type="tns:typeCredentials"/>
                    <xs:element minOccurs="0" name="certificateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="signaturePowerId" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeOpenSignSessionResp">
                <xs:sequence>
                    <xs:element name="sessionId" type="xs:string"/>
                    <xs:element name="message" type="tns:typeMessage"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeGetUserInfoReq">
                <xs:sequence>
                    <xs:element name="username" type="xs:string"/>
                    <xs:element name="ssn" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeGetUserInfoResp">
                <xs:sequence>
                    <xs:element minOccurs="0" name="user" type="tns:typeSigningUser"/>
                    <xs:element name="message" type="tns:typeMessage"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeSigningUser">
                <xs:sequence>
                    <xs:element name="user" type="tns:typeUser"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="certificates" nillable="true" type="tns:typeCertificate"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeCertificate">
                <xs:sequence>
                    <xs:element name="automatic" type="xs:boolean"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="hsmCerts" nillable="true" type="tns:typeHsmCert"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="processes" nillable="true" type="tns:typeProcess"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeHsmCert">
                <xs:sequence>
                    <xs:element name="serialNumber" type="xs:string"/>
                    <xs:element minOccurs="0" name="certificationAuthority" type="xs:string"/>
                    <xs:element minOccurs="0" name="validFrom" type="xs:string"/>
                    <xs:element minOccurs="0" name="validTo" type="xs:string"/>
                    <xs:element minOccurs="0" name="facilityId" type="xs:string"/>
                    <xs:element name="username" type="xs:string"/>
                    <xs:element minOccurs="0" name="hsm" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeProcess">
                <xs:sequence>
                    <xs:element name="code" type="xs:string"/>
                    <xs:element minOccurs="0" name="description" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="docTypes" nillable="true" type="tns:typeDocumentType"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeDocumentType">
                <xs:sequence>
                    <xs:element name="code" type="xs:string"/>
                    <xs:element name="description" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeSignDocReq">
                <xs:sequence>
                    <xs:element name="sessionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="automatic" type="xs:boolean"/>
                    <xs:element name="document" type="tns:typeDocument"/>
                    <xs:element name="signProperties" type="tns:typeSignProperties"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeDocument">
                <xs:sequence>
                    <xs:element minOccurs="0" name="docBin" type="xs:string"/>
                    <xs:element minOccurs="0" name="docHash" type="xs:string"/>
                    <xs:element name="docType" type="xs:string"/>
                    <xs:element name="signStringCode" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeSignProperties">
                <xs:sequence>
                    <xs:element name="signMode" type="xs:string"/>
                    <xs:element name="processId" type="xs:string"/>
                    <xs:element minOccurs="0" name="certificateSerialNumber" type="xs:string"/>
                    <xs:element minOccurs="0" name="parallel" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="padesProperties" type="tns:typePadesProperties"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typePadesProperties">
                <xs:sequence>
                    <xs:element minOccurs="0" name="pdfProfile" type="xs:string"/>
                    <xs:element minOccurs="0" name="location" type="xs:string"/>
                    <xs:element minOccurs="0" name="reason" type="xs:string"/>
                    <xs:element minOccurs="0" name="page" type="xs:string"/>
                    <xs:element minOccurs="0" name="leftx" type="xs:string"/>
                    <xs:element minOccurs="0" name="lefty" type="xs:string"/>
                    <xs:element minOccurs="0" name="rightx" type="xs:string"/>
                    <xs:element minOccurs="0" name="righty" type="xs:string"/>
                    <xs:element minOccurs="0" name="image" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeSignDocResp">
                <xs:sequence>
                    <xs:element name="sessionId" type="xs:string"/>
                    <xs:element minOccurs="0" name="signedDocBin" type="xs:string"/>
                    <xs:element minOccurs="0" name="signedDocHash" type="xs:string"/>
                    <xs:element name="message" type="tns:typeMessage"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeGetUserInfoReq2">
                <xs:sequence>
                    <xs:element name="username" type="xs:string"/>
                    <xs:element name="ssn" type="xs:string"/>
                    <xs:element minOccurs="0" name="processId" type="xs:string"/>
                    <xs:element minOccurs="0" name="docTypes" type="tns:typeDocTypeList"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeDocTypeList">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="doctype" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeGetUserInfoResp2">
                <xs:sequence>
                    <xs:element minOccurs="0" name="signerUser" type="tns:typeSigningUser2"/>
                    <xs:element name="message" type="tns:typeMessage"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeSigningUser2">
                <xs:sequence>
                    <xs:element name="user" type="tns:typeUser"/>
                    <xs:element minOccurs="0" name="signaturePowerList" type="tns:typeSignaturePowerList"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeSignOneDocResp">
                <xs:sequence>
                    <xs:element minOccurs="0" name="signedDocBin" type="xs:string"/>
                    <xs:element minOccurs="0" name="signedDocHash" type="xs:string"/>
                    <xs:element name="message" type="tns:typeMessage"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeCloseSignSessionResp">
                <xs:sequence>
                    <xs:element name="sessionId" type="xs:string"/>
                    <xs:element name="message" type="tns:typeMessage"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeCloseSignSessionReq">
                <xs:sequence>
                    <xs:element name="sessionId" type="xs:string"/>
                    <xs:element name="action" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeDespatchOtpResp">
                <xs:sequence>
                    <xs:element name="message" type="tns:typeMessage"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeSignOneDocReq">
                <xs:sequence>
                    <xs:element name="user" type="tns:typeUser"/>
                    <xs:element name="credentials" type="tns:typeCredentials"/>
                    <xs:element minOccurs="0" name="certificateId" type="xs:string"/>
                    <xs:element minOccurs="0" name="signaturePowerId" type="xs:string"/>
                    <xs:element name="document" type="tns:typeDocument"/>
                    <xs:element name="signProperties" type="tns:typeSignProperties"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeDespatchOtpReq">
                <xs:sequence>
                    <xs:element name="user" type="tns:typeUser"/>
                    <xs:element name="credentials" type="tns:typeCredentials"/>
                    <xs:element minOccurs="0" name="certificateId" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeSignaturePower">
                <xs:sequence>
                    <xs:element name="code" type="xs:string"/>
                    <xs:element minOccurs="0" name="description" type="xs:string"/>
                    <xs:element minOccurs="0" name="automatic" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="certificateList" type="tns:typeCertificateList"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="processes" nillable="true" type="tns:typeProcess"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeCert2">
                <xs:sequence>
                    <xs:element name="id" type="xs:string"/>
                    <xs:element minOccurs="0" name="serialNumber" type="xs:string"/>
                    <xs:element minOccurs="0" name="certificationAuthority" type="xs:string"/>
                    <xs:element minOccurs="0" name="validFrom" type="xs:string"/>
                    <xs:element minOccurs="0" name="validTo" type="xs:string"/>
                    <xs:element minOccurs="0" name="signLine" type="xs:string"/>
                    <xs:element minOccurs="0" name="description" type="xs:string"/>
                    <xs:element name="username" type="xs:string"/>
                    <xs:element minOccurs="0" name="hsm" type="xs:string"/>
                    <xs:element minOccurs="0" name="OTPtypeList" type="tns:typeOTPtypeList"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeOTPtypeList">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="OTPtype" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeCertificateList">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="certificate" nillable="true" type="tns:typeCert2"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="typeSignaturePowerList">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="signaturePower" nillable="true" type="tns:typeSignaturePower"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
  </wsdl:types>
  <wsdl:message name="DespatchOtp">
    <wsdl:part element="tns:DespatchOtpReq" name="DespatchOtpRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetUserInfo2Response">
    <wsdl:part element="tns:GetUserInfoResp2" name="GetUserInfoResponse2">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetUserInfo2">
    <wsdl:part element="tns:GetUserInfoReq2" name="GetUserInfoRequest2">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CertList">
    <wsdl:part element="tns:CertListReq" name="CertListRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SignDocResponse">
    <wsdl:part element="tns:SignDocResp" name="SignDocResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SignOneDoc">
    <wsdl:part element="tns:SignOneDocReq" name="SignOneDocRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="DespatchOtpResponse">
    <wsdl:part element="tns:DespatchOtpResp" name="DespatchOtpResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SignOneDocResponse">
    <wsdl:part element="tns:SignOneDocResp" name="SignOneDocResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CloseSignSessionResponse">
    <wsdl:part element="tns:CloseSignSessionResp" name="CloseSignSessionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="OpenSignSession">
    <wsdl:part element="tns:OpenSignSessionReq" name="OpenSignSessionRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetUserInfoResponse">
    <wsdl:part element="tns:GetUserInfoResp" name="GetUserInfoResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CloseSignSession">
    <wsdl:part element="tns:CloseSignSessionReq" name="CloseSignSessionRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="OpenSignSessionResponse">
    <wsdl:part element="tns:OpenSignSessionResp" name="OpenSignSessionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SignDoc">
    <wsdl:part element="tns:SignDocReq" name="SignDocRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CertListResponse">
    <wsdl:part element="tns:CertListResp" name="CertListResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetUserInfo">
    <wsdl:part element="tns:GetUserInfoReq" name="GetUserInfoRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ScrybaSignServerSync">
    <wsdl:operation name="CertList">
      <wsdl:input message="tns:CertList" name="CertList">
    </wsdl:input>
      <wsdl:output message="tns:CertListResponse" name="CertListResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="OpenSignSession">
      <wsdl:input message="tns:OpenSignSession" name="OpenSignSession">
    </wsdl:input>
      <wsdl:output message="tns:OpenSignSessionResponse" name="OpenSignSessionResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetUserInfo">
      <wsdl:input message="tns:GetUserInfo" name="GetUserInfo">
    </wsdl:input>
      <wsdl:output message="tns:GetUserInfoResponse" name="GetUserInfoResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SignDoc">
      <wsdl:input message="tns:SignDoc" name="SignDoc">
    </wsdl:input>
      <wsdl:output message="tns:SignDocResponse" name="SignDocResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetUserInfo2">
      <wsdl:input message="tns:GetUserInfo2" name="GetUserInfo2">
    </wsdl:input>
      <wsdl:output message="tns:GetUserInfo2Response" name="GetUserInfo2Response">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CloseSignSession">
      <wsdl:input message="tns:CloseSignSession" name="CloseSignSession">
    </wsdl:input>
      <wsdl:output message="tns:CloseSignSessionResponse" name="CloseSignSessionResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SignOneDoc">
      <wsdl:input message="tns:SignOneDoc" name="SignOneDoc">
    </wsdl:input>
      <wsdl:output message="tns:SignOneDocResponse" name="SignOneDocResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DespatchOtp">
      <wsdl:input message="tns:DespatchOtp" name="DespatchOtp">
    </wsdl:input>
      <wsdl:output message="tns:DespatchOtpResponse" name="DespatchOtpResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SyncSignServiceSoapBinding" type="tns:ScrybaSignServerSync">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CertList">
      <soap:operation soapAction="http://demo.medas-solutions.it/ScrybaSignServer/SyncSign/CertList" style="document"/>
      <wsdl:input name="CertList">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="CertListResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetUserInfo">
      <soap:operation soapAction="http://demo.medas-solutions.it/ScrybaSignServer/SyncSign/GetUserInfo" style="document"/>
      <wsdl:input name="GetUserInfo">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetUserInfoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="OpenSignSession">
      <soap:operation soapAction="http://demo.medas-solutions.it/ScrybaSignServer/SyncSign/OpenSignSession" style="document"/>
      <wsdl:input name="OpenSignSession">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="OpenSignSessionResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetUserInfo2">
      <soap:operation soapAction="http://demo.medas-solutions.it/ScrybaSignServer/SyncSign/GetUserInfo2" style="document"/>
      <wsdl:input name="GetUserInfo2">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetUserInfo2Response">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SignDoc">
      <soap:operation soapAction="http://demo.medas-solutions.it/ScrybaSignServer/SyncSign/SignDoc" style="document"/>
      <wsdl:input name="SignDoc">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="SignDocResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CloseSignSession">
      <soap:operation soapAction="http://demo.medas-solutions.it/ScrybaSignServer/SyncSign/CloseSignSession" style="document"/>
      <wsdl:input name="CloseSignSession">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="CloseSignSessionResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DespatchOtp">
      <soap:operation soapAction="http://demo.medas-solutions.it/ScrybaSignServer/SyncSign/DespatchOtp" style="document"/>
      <wsdl:input name="DespatchOtp">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="DespatchOtpResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SignOneDoc">
      <soap:operation soapAction="http://demo.medas-solutions.it/ScrybaSignServer/SyncSign/SignOneDoc" style="document"/>
      <wsdl:input name="SignOneDoc">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="SignOneDocResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SyncSignService">
    <wsdl:port binding="tns:SyncSignServiceSoapBinding" name="SyncSignServicePort">
      <soap:address location="https://scrybasign-cloud.medas-solutions.it/ScrybaSignServer/services/syncsign/v2.2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>